### ISSUE TITLE
Missä lähdekoodi?

### ISSUE THREAD

**Issue by Kaltsoon** [Terppa/tiralabra_periodi2#1]
Viikkoraportin perusteella toteutus olisi pitänyt alkaa 2. viikolla, mutta reposta ei löydy lähdekoodia. Unohditko lisätä muutokset?

**Comment by Terppa** [comment]
Hei.

Olin kyllä lisännyt lähdekoodin kansion ja jopa tarkistanut, että se näkyy
githubin repossa mutta en tietenkään ollut tarkistanut saako sitä auki.

Kansiossa oli liian monta tiedostoa enkä saanut siitä aamulla
virheilmoitusta. Siivosin sieltä turhat pois ja vaihdoin nimenkin varmuuden
vuoksi. Nyt se ainakin minulla aukeaa githubin puolella.

Eli lisää tarkkuutta seuraavien viikkojen palautuksiin :)

2016-11-14 15:00 GMT+02:00 Kalle Ilves <notifications@github.com>:

**Comment by Kaltsoon** [comment]
Awesome! Laitan sulle pisteet nyt 👍
